.libPaths(c("/tmp/claude-0/-home-user-MDIr/7d714999-05c1-566d-84c6-cb4710ea967b/scratchpad/lib_new", .libPaths())); suppressMessages(library(mdir)); options(mdir.quiet = TRUE)
source("bimodal_setup.R")
args <- commandArgs(TRUE); sep <- as.numeric(args[1])
d <- make_data(sep = sep)
b0 <- c(0.05, 0.3, 0.6, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1)
set.seed(7)
t0 <- Sys.time()
ad <- mdir:::adaptLadder(list(d$X), "MVN", b0, rounds = 4, R_pilot = 1500, K = 3)
cat("adaptation took", format(Sys.time() - t0), "\n")
for (i in seq_along(ad$history)) cat(sprintf("round %d rejection: %s\n", i, paste(round(ad$history[[i]]$rejection_rate, 2), collapse = " ")))
cat("final ladder:", round(ad$betas, 3), "\n")
f <- callMDI(list(d$X), R = 6000, thin = 5, types = "MVN", K = 3, betas = ad$betas, check_prior = FALSE, save_parameters = FALSE)
print(mdir:::ptDiagnostics(f))
a <- f$allocations[-(1:100), , 1]
pat <- apply(a, 1, group_partition, truth = d$truth)
cat("cold-chain pattern switches:", sum(pat[-1] != pat[-length(pat)]), " patterns:", paste(names(table(pat)), table(pat), collapse = "; "), "\n")
