// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// createSimilarityMat
arma::mat createSimilarityMat(arma::umat allocations);
RcppExport SEXP _mdir_createSimilarityMat(SEXP allocationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type allocations(allocationsSEXP);
    rcpp_result_gen = Rcpp::wrap(createSimilarityMat(allocations));
    return rcpp_result_gen;
END_RCPP
}
// gammaLogLikelihood
double gammaLogLikelihood(double x, double shape, double rate);
RcppExport SEXP _mdir_gammaLogLikelihood(SEXP xSEXP, SEXP shapeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(gammaLogLikelihood(x, shape, rate));
    return rcpp_result_gen;
END_RCPP
}
// invGammaLogLikelihood
double invGammaLogLikelihood(double x, double shape, double scale);
RcppExport SEXP _mdir_invGammaLogLikelihood(SEXP xSEXP, SEXP shapeSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(invGammaLogLikelihood(x, shape, scale));
    return rcpp_result_gen;
END_RCPP
}
// wishartLogLikelihood
double wishartLogLikelihood(arma::mat X, arma::mat V, double n, arma::uword P);
RcppExport SEXP _mdir_wishartLogLikelihood(SEXP XSEXP, SEXP VSEXP, SEXP nSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(wishartLogLikelihood(X, V, n, P));
    return rcpp_result_gen;
END_RCPP
}
// invWishartLogLikelihood
double invWishartLogLikelihood(arma::mat X, arma::mat Psi, double nu, arma::uword P);
RcppExport SEXP _mdir_invWishartLogLikelihood(SEXP XSEXP, SEXP PsiSEXP, SEXP nuSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(invWishartLogLikelihood(X, Psi, nu, P));
    return rcpp_result_gen;
END_RCPP
}
// mvtLogLikelihood
double mvtLogLikelihood(arma::vec x, arma::vec mu, arma::mat Sigma, double nu);
RcppExport SEXP _mdir_mvtLogLikelihood(SEXP xSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(mvtLogLikelihood(x, mu, Sigma, nu));
    return rcpp_result_gen;
END_RCPP
}
// pNorm
double pNorm(arma::vec x, arma::vec mu, arma::mat Sigma, bool is_sympd);
RcppExport SEXP _mdir_pNorm(SEXP xSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP is_sympdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type is_sympd(is_sympdSEXP);
    rcpp_result_gen = Rcpp::wrap(pNorm(x, mu, Sigma, is_sympd));
    return rcpp_result_gen;
END_RCPP
}
// densityHyperparameters
Rcpp::List densityHyperparameters(arma::mat X, arma::uword K, arma::uword mixture_type, arma::vec density_prior);
RcppExport SEXP _mdir_densityHyperparameters(SEXP XSEXP, SEXP KSEXP, SEXP mixture_typeSEXP, SEXP density_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type mixture_type(mixture_typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type density_prior(density_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(densityHyperparameters(X, K, mixture_type, density_prior));
    return rcpp_result_gen;
END_RCPP
}
// simulatePriorPredictiveCpp
Rcpp::List simulatePriorPredictiveCpp(arma::field<arma::mat> X, arma::uvec K, arma::uvec mixture_types, arma::uvec outlier_types, arma::uword n_datasets, arma::vec prior, arma::vec density_prior);
RcppExport SEXP _mdir_simulatePriorPredictiveCpp(SEXP XSEXP, SEXP KSEXP, SEXP mixture_typesSEXP, SEXP outlier_typesSEXP, SEXP n_datasetsSEXP, SEXP priorSEXP, SEXP density_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mixture_types(mixture_typesSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type outlier_types(outlier_typesSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_datasets(n_datasetsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type density_prior(density_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(simulatePriorPredictiveCpp(X, K, mixture_types, outlier_types, n_datasets, prior, density_prior));
    return rcpp_result_gen;
END_RCPP
}
// simulatePosteriorPredictiveCpp
Rcpp::List simulatePosteriorPredictiveCpp(arma::field<arma::mat> X, arma::uvec K, arma::uvec mixture_types, arma::uvec outlier_types, arma::field<arma::mat> parameters, arma::cube allocations, arma::cube outliers, arma::vec prior, arma::vec density_prior);
RcppExport SEXP _mdir_simulatePosteriorPredictiveCpp(SEXP XSEXP, SEXP KSEXP, SEXP mixture_typesSEXP, SEXP outlier_typesSEXP, SEXP parametersSEXP, SEXP allocationsSEXP, SEXP outliersSEXP, SEXP priorSEXP, SEXP density_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mixture_types(mixture_typesSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type outlier_types(outlier_typesSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type allocations(allocationsSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type outliers(outliersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type density_prior(density_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(simulatePosteriorPredictiveCpp(X, K, mixture_types, outlier_types, parameters, allocations, outliers, prior, density_prior));
    return rcpp_result_gen;
END_RCPP
}
// mdiNormalisingConstantCpp
double mdiNormalisingConstantCpp(arma::mat w, arma::uvec K, arma::mat phi);
RcppExport SEXP _mdir_mdiNormalisingConstantCpp(SEXP wSEXP, SEXP KSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(mdiNormalisingConstantCpp(w, K, phi));
    return rcpp_result_gen;
END_RCPP
}
// mdiWeightRateCpp
double mdiWeightRateCpp(arma::mat w, arma::uvec K, arma::mat phi, arma::uword lstar, arma::uword kstar);
RcppExport SEXP _mdir_mdiWeightRateCpp(SEXP wSEXP, SEXP KSEXP, SEXP phiSEXP, SEXP lstarSEXP, SEXP kstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type lstar(lstarSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type kstar(kstarSEXP);
    rcpp_result_gen = Rcpp::wrap(mdiWeightRateCpp(w, K, phi, lstar, kstar));
    return rcpp_result_gen;
END_RCPP
}
// mdiWeightRatesCpp
std::vector<double> mdiWeightRatesCpp(arma::mat w, arma::uvec K, arma::mat phi, arma::uword lstar);
RcppExport SEXP _mdir_mdiWeightRatesCpp(SEXP wSEXP, SEXP KSEXP, SEXP phiSEXP, SEXP lstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type lstar(lstarSEXP);
    rcpp_result_gen = Rcpp::wrap(mdiWeightRatesCpp(w, K, phi, lstar));
    return rcpp_result_gen;
END_RCPP
}
// mdiPhiRateCpp
double mdiPhiRateCpp(arma::mat w, arma::uvec K, arma::mat phi, arma::uword l, arma::uword m);
RcppExport SEXP _mdir_mdiPhiRateCpp(SEXP wSEXP, SEXP KSEXP, SEXP phiSEXP, SEXP lSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type l(lSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(mdiPhiRateCpp(w, K, phi, l, m));
    return rcpp_result_gen;
END_RCPP
}
// mvtImputationCheckCpp
Rcpp::List mvtImputationCheckCpp(arma::mat X, arma::uvec missing_cols, arma::uword n_rep);
RcppExport SEXP _mdir_mvtImputationCheckCpp(SEXP XSEXP, SEXP missing_colsSEXP, SEXP n_repSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type missing_cols(missing_colsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_rep(n_repSEXP);
    rcpp_result_gen = Rcpp::wrap(mvtImputationCheckCpp(X, missing_cols, n_rep));
    return rcpp_result_gen;
END_RCPP
}
// calibrateInverseGammaCpp
arma::vec calibrateInverseGammaCpp(double lower, double upper, double tail);
RcppExport SEXP _mdir_calibrateInverseGammaCpp(SEXP lowerSEXP, SEXP upperSEXP, SEXP tailSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type tail(tailSEXP);
    rcpp_result_gen = Rcpp::wrap(calibrateInverseGammaCpp(lower, upper, tail));
    return rcpp_result_gen;
END_RCPP
}
// gpPopulationCheckCpp
arma::mat gpPopulationCheckCpp(arma::vec y, double centre, double center_sd, double pool_sd_scale, arma::uword n_iter);
RcppExport SEXP _mdir_gpPopulationCheckCpp(SEXP ySEXP, SEXP centreSEXP, SEXP center_sdSEXP, SEXP pool_sd_scaleSEXP, SEXP n_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type centre(centreSEXP);
    Rcpp::traits::input_parameter< double >::type center_sd(center_sdSEXP);
    Rcpp::traits::input_parameter< double >::type pool_sd_scale(pool_sd_scaleSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter(n_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(gpPopulationCheckCpp(y, centre, center_sd, pool_sd_scale, n_iter));
    return rcpp_result_gen;
END_RCPP
}
// readMCMCsamples
arma::mat readMCMCsamples(arma::uword n_samples, arma::uword n_params, std::string load_dir);
RcppExport SEXP _mdir_readMCMCsamples(SEXP n_samplesSEXP, SEXP n_paramsSEXP, SEXP load_dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_params(n_paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type load_dir(load_dirSEXP);
    rcpp_result_gen = Rcpp::wrap(readMCMCsamples(n_samples, n_params, load_dir));
    return rcpp_result_gen;
END_RCPP
}
// runMDI
Rcpp::List runMDI(arma::uword R, arma::uword thin, arma::field<arma::mat> Y, arma::uvec K, arma::uvec mixture_types, arma::uvec outlier_types, arma::umat labels, arma::umat fixed, arma::field< arma::vec > proposal_windows, bool save_parameters, bool save_imputed, arma::vec prior, arma::vec density_prior);
RcppExport SEXP _mdir_runMDI(SEXP RSEXP, SEXP thinSEXP, SEXP YSEXP, SEXP KSEXP, SEXP mixture_typesSEXP, SEXP outlier_typesSEXP, SEXP labelsSEXP, SEXP fixedSEXP, SEXP proposal_windowsSEXP, SEXP save_parametersSEXP, SEXP save_imputedSEXP, SEXP priorSEXP, SEXP density_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mixture_types(mixture_typesSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type outlier_types(outlier_typesSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< arma::field< arma::vec > >::type proposal_windows(proposal_windowsSEXP);
    Rcpp::traits::input_parameter< bool >::type save_parameters(save_parametersSEXP);
    Rcpp::traits::input_parameter< bool >::type save_imputed(save_imputedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type density_prior(density_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(runMDI(R, thin, Y, K, mixture_types, outlier_types, labels, fixed, proposal_windows, save_parameters, save_imputed, prior, density_prior));
    return rcpp_result_gen;
END_RCPP
}
// runMDIWriteToFile
void runMDIWriteToFile(arma::uword R, arma::uword thin, arma::field<arma::mat> Y, arma::uvec K, arma::uvec mixture_types, arma::uvec outlier_types, arma::umat labels, arma::umat fixed, arma::field< arma::vec > proposal_windows, std::string save_dir, arma::vec prior, arma::vec density_prior);
RcppExport SEXP _mdir_runMDIWriteToFile(SEXP RSEXP, SEXP thinSEXP, SEXP YSEXP, SEXP KSEXP, SEXP mixture_typesSEXP, SEXP outlier_typesSEXP, SEXP labelsSEXP, SEXP fixedSEXP, SEXP proposal_windowsSEXP, SEXP save_dirSEXP, SEXP priorSEXP, SEXP density_priorSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mixture_types(mixture_typesSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type outlier_types(outlier_typesSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< arma::field< arma::vec > >::type proposal_windows(proposal_windowsSEXP);
    Rcpp::traits::input_parameter< std::string >::type save_dir(save_dirSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type density_prior(density_priorSEXP);
    runMDIWriteToFile(R, thin, Y, K, mixture_types, outlier_types, labels, fixed, proposal_windows, save_dir, prior, density_prior);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mdir_createSimilarityMat", (DL_FUNC) &_mdir_createSimilarityMat, 1},
    {"_mdir_gammaLogLikelihood", (DL_FUNC) &_mdir_gammaLogLikelihood, 3},
    {"_mdir_invGammaLogLikelihood", (DL_FUNC) &_mdir_invGammaLogLikelihood, 3},
    {"_mdir_wishartLogLikelihood", (DL_FUNC) &_mdir_wishartLogLikelihood, 4},
    {"_mdir_invWishartLogLikelihood", (DL_FUNC) &_mdir_invWishartLogLikelihood, 4},
    {"_mdir_mvtLogLikelihood", (DL_FUNC) &_mdir_mvtLogLikelihood, 4},
    {"_mdir_pNorm", (DL_FUNC) &_mdir_pNorm, 4},
    {"_mdir_densityHyperparameters", (DL_FUNC) &_mdir_densityHyperparameters, 4},
    {"_mdir_simulatePriorPredictiveCpp", (DL_FUNC) &_mdir_simulatePriorPredictiveCpp, 7},
    {"_mdir_simulatePosteriorPredictiveCpp", (DL_FUNC) &_mdir_simulatePosteriorPredictiveCpp, 9},
    {"_mdir_mdiNormalisingConstantCpp", (DL_FUNC) &_mdir_mdiNormalisingConstantCpp, 3},
    {"_mdir_mdiWeightRateCpp", (DL_FUNC) &_mdir_mdiWeightRateCpp, 5},
    {"_mdir_mdiWeightRatesCpp", (DL_FUNC) &_mdir_mdiWeightRatesCpp, 4},
    {"_mdir_mdiPhiRateCpp", (DL_FUNC) &_mdir_mdiPhiRateCpp, 5},
    {"_mdir_mvtImputationCheckCpp", (DL_FUNC) &_mdir_mvtImputationCheckCpp, 3},
    {"_mdir_calibrateInverseGammaCpp", (DL_FUNC) &_mdir_calibrateInverseGammaCpp, 3},
    {"_mdir_gpPopulationCheckCpp", (DL_FUNC) &_mdir_gpPopulationCheckCpp, 5},
    {"_mdir_readMCMCsamples", (DL_FUNC) &_mdir_readMCMCsamples, 3},
    {"_mdir_runMDI", (DL_FUNC) &_mdir_runMDI, 13},
    {"_mdir_runMDIWriteToFile", (DL_FUNC) &_mdir_runMDIWriteToFile, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_mdir(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
